name: Process Design Tokens

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'design-tokens.json'

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Debug workflow context
        run: |
          echo "::group::Workflow Context"
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "::endgroup::"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Debug repository state
        run: |
          echo "::group::Debug Repository State"
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status
          echo "::endgroup::"

      - name: Configure Git
        run: |
          git config --global user.name 'Design Tokens Bot'
          git config --global user.email 'design-tokens-bot@portland.gov'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Debug file system
        run: |
          echo "::group::Debug File System"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "::endgroup::"

      - name: Process tokens
        id: process-tokens
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "::group::Processing Tokens"
          
          # Check if design-tokens.json exists
          if [ ! -f design-tokens.json ]; then
            echo "::error::design-tokens.json not found"
            exit 1
          fi
          
          echo "Found design-tokens.json"
          echo "File contents:"
          cat design-tokens.json
          
          # Create output directory
          mkdir -p output
          echo "Created output directory"
          
          # Process tokens with verbose logging
          echo "Running token processing..."
          node src/cli.js --source file --input design-tokens.json --output output
          
          # Check if output files were created
          echo "Checking for output files..."
          ls -la output/
          
          if [ ! -f output/tokens.css ] || [ ! -f output/tokens.json ]; then
            echo "::error::Output files were not created"
            exit 1
          fi
          
          echo "::notice::Tokens were processed successfully"
          echo "::endgroup::"

      - name: Commit and push changes
        run: |
          echo "::group::Committing and pushing changes"
          
          # Stage all changes
          git add output/
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "::notice::No changes to commit"
            exit 0
          fi
          
          # Commit changes
          git commit -m "chore: process design tokens
          
          Automated token processing via GitHub Actions.
          This commit adds the processed token files based on changes in design-tokens.json."
          
          # Push changes back to the PR branch
          git push origin HEAD
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Notify on failure
      #   if: failure()
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #       --data '{"text":"❌ Failed to process design tokens\nWorkflow: ${{ github.workflow }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
      #       ${{ secrets.SLACK_WEBHOOK_URL }}
