name: Process Design Tokens

on:
  pull_request:
    branches:
      - main
    paths:
      - 'design-tokens.json'
      - '.github/workflows/process-tokens.yml'

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Process tokens
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
        run: |
          pnpm run process-tokens -- --source file --input design-tokens.json --output ./output

      - name: Configure Git
        run: |
          git config --global user.name 'Design Tokens Bot'
          git config --global user.email 'design-tokens-bot@portland.gov'

      - name: Update PR with processed tokens
        run: |
          # Copy processed files
          cp -r output/* .
          
          # Commit changes
          git add .
          git commit -m "Update processed design tokens"
          
          # Push changes to PR branch
          git push origin ${{ github.head_ref }}

      - name: Validate changes
        run: |
          pnpm run validate

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '✅ Design tokens have been processed and validated successfully.\n\nChanges include:\n- Updated design tokens\n- Generated CSS variables\n- Generated JSON output'
            }) 
